export default[
    {
        id:0,
        brandname:'别克', //品牌名称
        carname:'GL6', //车型名称
        modelname:'', //车款名称
        imgurl:"http://47.105.100.82/0605/image600/Car_image_001.png",
        video:{
            url:"http://47.105.100.82/0605/Carvideo2400/Car_solo_001.mp4",
            url2:"http://47.105.100.82/0605/Carvideo1200/Car_compare_001.mp4",
            urlRoot:'http://47.105.100.82/0605/Merge/Car_compare',
            videoNum:'001',
            duration:360,                 //秒,
            slot:[
                {                         //时间段
                    time:0,
                    title:'亮点'
                },
                {
                    time:130, //130
                    title:'外观'
                },
                {
                    time:203,
                    title:'空间'
                },
                {
                    time:221,
                    title:'内饰'
                }
            ],
            twoslot:[
                {                         //时间段
                    time:0,
                    title:'外观'
                },
                {
                    time:73,
                    title:'空间'
                },
                {
                    time:91,
                    title:'内饰'
                }
            ],
            coords:[
                    {
                        start:0,
                        url:'../img/1_car.jpg'
                    },{
                        start:10,
                        url:'../img/2_car.jpg'
                    },{
                        start:20,
                        url:'../img/3_car.jpg'
                    },{
                        start:30,
                        url:'../img/4_car.jpg'
                    },{
                        start:40,
                        url:'../img/5_car.jpg'
                    },{
                        start:50,
                        url:'../img/6_car.jpg'
                    },{
                        start:60,
                        url:'../img/7_car.jpg'
                    },{
                        start:70,
                        url:'../img/8_car.jpg'
                    },{
                        start:80,
                        url:'../img/9_car.jpg'
                    },{
                        start:90,
                        url:'../img/10_car.jpg'
                    }
            ]
        },
        koubei:{
                detail:[
                    {                   //配置
                        title:'动力',
                        desc:'动力性能很好，起步有点肉但后段加速特给力'
                    },{
                        title:'舒适性',
                        desc:'舒适性不错，静音效果非常不错，悬挂避震效果好'
                    },{
                        title:'空间',
                        desc:'整体空间大但后备箱空间不够，第二排腿部空间宽敞'
                    },{
                        title:'外观',
                        desc:'LED大灯显眼，前脸看起来很帅很大气'
                    },{
                        title:'操控',
                        desc:'操控不错，转向精准，底盘悬挂不错'
                    },{
                        title:'内饰',
                        desc:'内饰做工、风格蛮豪华，皮座椅舒服，方向盘手感好'
                    },{
                        title:'油耗',
                        desc:'油耗表现不错，油耗不高，高速上油耗低'
                    },{
                        title:'配置',
                        desc:'配置高，音响效果不错，有自动泊车功能'
                    }
                ]
        }

    },
    {
        id:1,
        brandname:'福特', //品牌名称
        carname:'金牛座', //车型名称
        modelname:'', //车款名称
        imgurl:"http://47.105.100.82/0605/image600/Car_image_002.png",
        video:{
            url:"http://47.105.100.82/0605/Carvideo2400/Car_solo_002.mp4",
            url2:"http://47.105.100.82/0605/Carvideo1200/Car_compare_002.mp4",
            urlRoot:'http://47.105.100.82/0605/Merge/Car_compare',
            videoNum:'002',
            duration:360,                 //秒,
              slot:[
              {                         //时间段
                  time:0,
                  title:'亮点'
              },
              {
                  time:250,
                  title:'外观'
              },
              {
                  time:325,
                  title:'空间'
              },
              {
                  time:341,
                  title:'内饰'
              }
            ],
            twoslot:[
                {                         //时间段
                    time:0,
                    title:'外观'
                },
                {
                    time:73,
                    title:'空间'
                },
                {
                    time:91,
                    title:'内饰'
                }
            ],
            coords:[
                    {
                        start:0,
                        url:'../img/1_car.jpg'
                    },{
                        start:10,
                        url:'../img/2_car.jpg'
                    },{
                        start:20,
                        url:'../img/3_car.jpg'
                    },{
                        start:30,
                        url:'../img/4_car.jpg'
                    },{
                        start:40,
                        url:'../img/5_car.jpg'
                    },{
                        start:50,
                        url:'../img/6_car.jpg'
                    },{
                        start:60,
                        url:'../img/7_car.jpg'
                    },{
                        start:70,
                        url:'../img/8_car.jpg'
                    },{
                        start:80,
                        url:'../img/9_car.jpg'
                    },{
                        start:90,
                        url:'../img/10_car.jpg'
                    }
            ]
        },
        koubei:{
                detail:[
                    {                   //配置
                        title:'动力',
                        desc:'动力表现很强，但是起步肉，高速超车很轻松'
                    },{
                        title:'舒适性',
                        desc:'舒适性不错，隔音效果挺好，车内异响'
                    },{
                        title:'空间',
                        desc:'后备箱空间大，第二排空间大，储物空间超级大'
                    },{
                        title:'外观',
                        desc:'车头造型非常霸气，LED大灯组吸引，车漆偏薄'
                    },{
                        title:'操控',
                        desc:'操控不错，指向准确，上坡平顺'
                    },{
                        title:'内饰',
                        desc:'内饰做工考究，桃木内饰不太喜欢，新车味道大'
                    },{
                        title:'油耗',
                        desc:'新车油耗蛮高，城里2.0t高功率不省油'
                    },{
                        title:'配置',
                        desc:'配置高，音响效果蛮不错，车载导航系统坑爹'
                    }
                ]
        }

    },
    {
        id:2,
        brandname:'雪铁龙', //品牌名称
        carname:'C6', //车型名称
        modelname:'', //车款名称
        imgurl:"http://47.105.100.82/0605/image600/Car_image_003.png",
        video:{
            url:"http://47.105.100.82/0605/Carvideo2400/Car_solo_003.mp4",
            url2:"http://47.105.100.82/0605/Carvideo1200/Car_compare_003.mp4",
            urlRoot:'http://47.105.100.82/0605/Merge/Car_compare',
            videoNum:'003',
            duration:360,                 //秒,
            slot:[
                {                         //时间段
                    time:0,
                    title:'亮点'
                },
                {
                    time:250,
                    title:'外观'
                },
                {
                    time:325,
                    title:'空间'
                },
                {
                    time:341,
                    title:'内饰'
                }
            ],
            twoslot:[
                {                         //时间段
                    time:0,
                    title:'外观'
                },
                {
                    time:73,
                    title:'空间'
                },
                {
                    time:91,
                    title:'内饰'
                }
            ],
            coords:[
                    {
                        start:0,
                        url:'../img/1_car.jpg'
                    },{
                        start:10,
                        url:'../img/2_car.jpg'
                    },{
                        start:20,
                        url:'../img/3_car.jpg'
                    },{
                        start:30,
                        url:'../img/4_car.jpg'
                    },{
                        start:40,
                        url:'../img/5_car.jpg'
                    },{
                        start:50,
                        url:'../img/6_car.jpg'
                    },{
                        start:60,
                        url:'../img/7_car.jpg'
                    },{
                        start:70,
                        url:'../img/8_car.jpg'
                    },{
                        start:80,
                        url:'../img/9_car.jpg'
                    },{
                        start:90,
                        url:'../img/10_car.jpg'
                    }
            ]
        },
        koubei:{
                detail:[
                    {                   //配置
                        title:'动力',
                        desc:'加速动力十足，换挡平顺'
                    },{
                        title:'舒适性',
                        desc:'舒适性满意，隔音玻璃相当不错，底盘过滤效果很好'
                    },{
                        title:'空间',
                        desc:'空间大，后排空间相当大，后备箱空间小'
                    },{
                        title:'外观',
                        desc:'LED大灯喜欢，前脸设计稳重，车尾造型喜欢'
                    },{
                        title:'操控',
                        desc:'底盘超稳，操控不错，指向性准确'
                    },{
                        title:'内饰',
                        desc:'内饰做工好，内饰的用料和风格喜欢'
                    },{
                        title:'油耗',
                        desc:'油耗方面满意，发动机启停好用，市区油耗蛮多'
                    },{
                        title:'配置',
                        desc:'配置高，音响效果挺好，车载导航不好用'
                    }
                ]
        }

    },
    {
        id:3,
        brandname:'雪佛兰', //品牌名称
        carname:'迈锐宝XL', //车型名称
        modelname:'', //车款名称
        imgurl:"http://47.105.100.82/0605/image600/Car_image_004.png",
        video:{
            url:"http://47.105.100.82/0605/Carvideo2400/Car_solo_004.mp4",
            url2:"http://47.105.100.82/0605/Carvideo1200/Car_compare_004.mp4",
            urlRoot:'http://47.105.100.82/0605/Merge/Car_compare',
            videoNum:'004',
            duration:360,                 //秒,
            slot:[
                {                         //时间段
                    time:0,
                    title:'亮点'
                },
                {
                    time:250,
                    title:'外观'
                },
                {
                    time:325,
                    title:'空间'
                },
                {
                    time:341,
                    title:'内饰'
                }
            ],
            twoslot:[
                {                         //时间段
                    time:0,
                    title:'外观'
                },
                {
                    time:73,
                    title:'空间'
                },
                {
                    time:91,
                    title:'内饰'
                }
            ],
            coords:[
                    {
                        start:0,
                        url:'../img/1_car.jpg'
                    },{
                        start:10,
                        url:'../img/2_car.jpg'
                    },{
                        start:20,
                        url:'../img/3_car.jpg'
                    },{
                        start:30,
                        url:'../img/4_car.jpg'
                    },{
                        start:40,
                        url:'../img/5_car.jpg'
                    },{
                        start:50,
                        url:'../img/6_car.jpg'
                    },{
                        start:60,
                        url:'../img/7_car.jpg'
                    },{
                        start:70,
                        url:'../img/8_car.jpg'
                    },{
                        start:80,
                        url:'../img/9_car.jpg'
                    },{
                        start:90,
                        url:'../img/10_car.jpg'
                    }
            ]
        },
        koubei:{
                detail:[
                    {                   //配置
                        title:'动力',
                        desc:'动力完全够用，加速性能好，D档起步比较肉'
                    },{
                        title:'舒适性',
                        desc:'隔音效果好，胎噪大，震动过滤好'
                    },{
                        title:'空间',
                        desc:'空间大，后备箱空间比较大，后排空间宽敞'
                    },{
                        title:'外观',
                        desc:'前脸设计大气，车头大灯很犀利，车子车漆偏薄'
                    },{
                        title:'操控',
                        desc:'操控不错，车子底盘蛮扎实，指向精准'
                    },{
                        title:'内饰',
                        desc:'车子做工不错，内饰塑料件较多，座椅材质好'
                    },{
                        title:'油耗',
                        desc:'油耗表现较满意，启停系统不好，市区油耗方面高'
                    },{
                        title:'配置',
                        desc:'倒车影像不方便，音响效果挺好，没有定速巡航功能'
                    }
                ]
        }

    }, {
        id:4,
        brandname:'大众', //品牌名称
        carname:'途昂', //车型名称
        modelname:'', //车款名称
        imgurl:"http://47.105.100.82/0605/image600/Car_image_005.png",
        video:{
            url:"http://47.105.100.82/0605/Carvideo2400/Car_solo_005.mp4",
            url2:"http://47.105.100.82/0605/Carvideo1200/Car_compare_005.mp4",
            urlRoot:'http://47.105.100.82/0605/Merge/Car_compare',
            videoNum:'005',
            duration:360,                 //秒,
            slot:[
                {                         //时间段
                    time:0,
                    title:'亮点'
                },
                {
                    time:250, 
                    title:'外观'
                },
                {
                    time:325,
                    title:'空间'
                },
                {
                    time:341,
                    title:'内饰'
                }
            ],
            twoslot:[
                {                         //时间段
                    time:0,
                    title:'外观'
                },
                {
                    time:73,
                    title:'空间'
                },
                {
                    time:91,
                    title:'内饰'
                }
            ],
            coords:[
                    {
                        start:0,
                        url:'../img/1_car.jpg'
                    },{
                        start:10,
                        url:'../img/2_car.jpg'
                    },{
                        start:20,
                        url:'../img/3_car.jpg'
                    },{
                        start:30,
                        url:'../img/4_car.jpg'
                    },{
                        start:40,
                        url:'../img/5_car.jpg'
                    },{
                        start:50,
                        url:'../img/6_car.jpg'
                    },{
                        start:60,
                        url:'../img/7_car.jpg'
                    },{
                        start:70,
                        url:'../img/8_car.jpg'
                    },{
                        start:80,
                        url:'../img/9_car.jpg'
                    },{
                        start:90,
                        url:'../img/10_car.jpg'
                    }
            ]
        },
        koubei:{
                detail:[
                    {                   //配置
                        title:'动力',
                        desc:'动力充沛，起步肉后面提速快，顿挫感蛮强烈'
                    },{
                        title:'舒适性',
                        desc:'舒适性不错，隔音效果好，空调挺给力'
                    },{
                        title:'空间',
                        desc:'空间大，后排空间强大，后备箱空间真心大'
                    },{
                        title:'外观',
                        desc:'LED大灯给力，车漆较薄，前脸看起来特别宽'
                    },{
                        title:'操控',
                        desc:'操控不错，底盘扎实，指向精准，路感反馈好'
                    },{
                        title:'内饰',
                        desc:'内饰做工，用料好，味道特别大，按钮比较方便'
                    },{
                        title:'油耗',
                        desc:'综合油耗多一些，高速上油耗不错，城区油耗挺高'
                    },{
                        title:'配置',
                        desc:'配置高，音响效果特别完美，有定速巡航系统'
                    }
                ]
        }

    },
    {
        id:5,
        brandname:'广汽传祺', //品牌名称
        carname:'GS8', //车型名称
        modelname:'', //车款名称
        imgurl:"http://47.105.100.82/0605/image600/Car_image_006.png",
        video:{
            url:"http://47.105.100.82/0605/Carvideo2400/Car_solo_006.mp4",
            url2:"http://47.105.100.82/0605/Carvideo1200/Car_compare_006.mp4",
            urlRoot:'http://47.105.100.82/0605/Merge/Car_compare',
            videoNum:'006',
            duration:360,                 //秒,
            slot:[
                {                         //时间段
                    time:0,
                    title:'亮点'
                },
                {
                    time:130,
                    title:'外观'
                },
                {
                    time:203,
                    title:'空间'
                },
                {
                    time:221,
                    title:'内饰'
                }
            ],
            twoslot:[
                {                         //时间段
                    time:0,
                    title:'外观'
                },
                {
                    time:73,
                    title:'空间'
                },
                {
                    time:91,
                    title:'内饰'
                }
            ],
            coords:[
                    {
                        start:0,
                        url:'../img/1_car.jpg'
                    },{
                        start:10,
                        url:'../img/2_car.jpg'
                    },{
                        start:20,
                        url:'../img/3_car.jpg'
                    },{
                        start:30,
                        url:'../img/4_car.jpg'
                    },{
                        start:40,
                        url:'../img/5_car.jpg'
                    },{
                        start:50,
                        url:'../img/6_car.jpg'
                    },{
                        start:60,
                        url:'../img/7_car.jpg'
                    },{
                        start:70,
                        url:'../img/8_car.jpg'
                    },{
                        start:80,
                        url:'../img/9_car.jpg'
                    },{
                        start:90,
                        url:'../img/10_car.jpg'
                    }
            ]
        },
        koubei:{
                detail:[
                    {                   //配置
                        title:'动力',
                        desc:'加速动力十足，换挡平顺'
                    },{
                        title:'舒适性',
                        desc:'座椅材料舒适性较好，高速胎噪控制较差'
                    },{
                        title:'空间',
                        desc:'乘坐空间较大，腿部空间够用，储物空间有限'
                    },{
                        title:'外观',
                        desc:'尾灯帅，侧面腰线好看'
                    },{
                        title:'操控',
                        desc:'路感反馈清洗，转向精准，底盘悬挂扎实'
                    },{
                        title:'内饰',
                        desc:'内饰做工精准，气氛灯好看'
                    },{
                        title:'油耗',
                        desc:'高速油耗满意，室内可经济模式省油'
                    },{
                        title:'配置',
                        desc:'自动加速定速巡航好用，主动刹车时亮点'
                    }
                ]
        }

    },
    {
        id:6,
        brandname:'福特', //品牌名称
        carname:'福克斯', //车型名称
        modelname:'', //车款名称
        imgurl:"http://47.105.100.82/0605/image600/Car_image_007.png",
        video:{
            url:"http://47.105.100.82/0605/Carvideo2400/Car_solo_007.mp4",
            url2:"http://47.105.100.82/0605/Carvideo1200/Car_compare_007.mp4",
            urlRoot:'http://47.105.100.82/0605/Merge/Car_compare',
            videoNum:'007',
            duration:360,                 //秒,
            slot:[
                {                         //时间段
                    time:0,
                    title:'亮点'
                },
                {
                    time:130,
                    title:'外观'
                },
                {
                    time:203,
                    title:'空间'
                },
                {
                    time:221,
                    title:'内饰'
                }
            ],
            twoslot:[
                {                         //时间段
                    time:0,
                    title:'外观'
                },
                {
                    time:73,
                    title:'空间'
                },
                {
                    time:91,
                    title:'内饰'
                }
            ],
            coords:[
                    {
                        start:0,
                        url:'../img/1_car.jpg'
                    },{
                        start:10,
                        url:'../img/2_car.jpg'
                    },{
                        start:20,
                        url:'../img/3_car.jpg'
                    },{
                        start:30,
                        url:'../img/4_car.jpg'
                    },{
                        start:40,
                        url:'../img/5_car.jpg'
                    },{
                        start:50,
                        url:'../img/6_car.jpg'
                    },{
                        start:60,
                        url:'../img/7_car.jpg'
                    },{
                        start:70,
                        url:'../img/8_car.jpg'
                    },{
                        start:80,
                        url:'../img/9_car.jpg'
                    },{
                        start:90,
                        url:'../img/10_car.jpg'
                    }
            ]
        },
        koubei:{
                detail:[
                    {                   //配置
                        title:'动力',
                        desc:'动力响应及时，起步比较慢，响应速度蛮快'
                    },{
                        title:'舒适性',
                        desc:'舒适性不错，隔音效果很好，震动过滤特好'
                    },{
                        title:'空间',
                        desc:'横向空间不错，储物空间充足，后备箱空间超级大'
                    },{
                        title:'外观',
                        desc:'LED大灯帅气，车身漆面较薄，前脸设计漂亮'
                    },{
                        title:'操控',
                        desc:'操控不错，底盘挺扎实，指向精准，路感反馈特别清晰'
                    },{
                        title:'内饰',
                        desc:'内饰质感特好，内饰用料大气，新车味道大'
                    },{
                        title:'油耗',
                        desc:'油耗不是很高，城区油耗偏高，定速巡航油耗低'
                    },{
                        title:'配置',
                        desc:'配置丰富，车内音响不满意，车载导航不好'
                    }
                ]
        }

    },
    {
        id:7,
        brandname:'日产', //品牌名称
        carname:'劲客', //车型名称
        modelname:'', //车款名称
        imgurl:"http://47.105.100.82/0605/image600/Car_image_008.png",
        video:{
            url:"http://47.105.100.82/0605/Carvideo2400/Car_solo_008.mp4",
            url2:"http://47.105.100.82/0605/Carvideo1200/Car_compare_008.mp4",
            urlRoot:'http://47.105.100.82/0605/Merge/Car_compare',
            videoNum:'008',
            duration:360,                 //秒,
            slot:[
                {                         //时间段
                    time:0,
                    title:'亮点'
                },
                {
                    time:130,
                    title:'外观'
                },
                {
                    time:203,
                    title:'空间'
                },
                {
                    time:221,
                    title:'内饰'
                }
            ],
            twoslot:[
                {                         //时间段
                    time:0,
                    title:'外观'
                },
                {
                    time:73,
                    title:'空间'
                },
                {
                    time:91,
                    title:'内饰'
                }
            ],
            coords:[
                    {
                        start:0,
                        url:'../img/1_car.jpg'
                    },{
                        start:10,
                        url:'../img/2_car.jpg'
                    },{
                        start:20,
                        url:'../img/3_car.jpg'
                    },{
                        start:30,
                        url:'../img/4_car.jpg'
                    },{
                        start:40,
                        url:'../img/5_car.jpg'
                    },{
                        start:50,
                        url:'../img/6_car.jpg'
                    },{
                        start:60,
                        url:'../img/7_car.jpg'
                    },{
                        start:70,
                        url:'../img/8_car.jpg'
                    },{
                        start:80,
                        url:'../img/9_car.jpg'
                    },{
                        start:90,
                        url:'../img/10_car.jpg'
                    }
            ]
        },
        koubei:{
                detail:[
                    {                   //配置
                        title:'动力',
                        desc:'加速动力十足，换挡平顺'
                    },{
                        title:'舒适性',
                        desc:'座椅材料舒适性较好，高速胎噪控制较差'
                    },{
                        title:'空间',
                        desc:'乘坐空间较大，腿部空间够用，储物空间有限'
                    },{
                        title:'外观',
                        desc:'尾灯帅，侧面腰线好看'
                    },{
                        title:'操控',
                        desc:'路感反馈清洗，转向精准，底盘悬挂扎实'
                    },{
                        title:'内饰',
                        desc:'内饰做工精准，气氛灯好看'
                    },{
                        title:'油耗',
                        desc:'高速油耗满意，室内可经济模式省油'
                    },{
                        title:'配置',
                        desc:'自动加速定速巡航好用，主动刹车时亮点'
                    }
                ]
        }

    },
    {
        id:8,
        brandname:'雪铁龙', //品牌名称
        carname:'天逸C5 AIRCROSS', //车型名称
        modelname:'', //车款名称
        imgurl:"http://47.105.100.82/0605/image600/Car_image_009.png",
        video:{
            url:"http://47.105.100.82/0605/Carvideo2400/Car_solo_009.mp4",
            url2:"http://47.105.100.82/0605/Carvideo1200/Car_compare_009.mp4",
            urlRoot:'http://47.105.100.82/0605/Merge/Car_compare',
            videoNum:'009',
            duration:360,                 //秒,
            slot:[
                {                         //时间段
                    time:0,
                    title:'亮点'
                },
                {
                    time:130,
                    title:'外观'
                },
                {
                    time:203,
                    title:'空间'
                },
                {
                    time:221,
                    title:'内饰'
                }
            ],
            twoslot:[
                {                         //时间段
                    time:0,
                    title:'外观'
                },
                {
                    time:73,
                    title:'空间'
                },
                {
                    time:91,
                    title:'内饰'
                }
            ],
            coords:[
                    {
                        start:0,
                        url:'../img/1_car.jpg'
                    },{
                        start:10,
                        url:'../img/2_car.jpg'
                    },{
                        start:20,
                        url:'../img/3_car.jpg'
                    },{
                        start:30,
                        url:'../img/4_car.jpg'
                    },{
                        start:40,
                        url:'../img/5_car.jpg'
                    },{
                        start:50,
                        url:'../img/6_car.jpg'
                    },{
                        start:60,
                        url:'../img/7_car.jpg'
                    },{
                        start:70,
                        url:'../img/8_car.jpg'
                    },{
                        start:80,
                        url:'../img/9_car.jpg'
                    },{
                        start:90,
                        url:'../img/10_car.jpg'
                    }
            ]
        },
        koubei:{
                detail:[
                    {                   //配置
                        title:'动力',
                        desc:'动力好，超车特轻松，起步容易，油门响应灵敏'
                    },{
                        title:'舒适性',
                        desc:'隔音效果不错，驾驶感特好，底盘过滤好'
                    },{
                        title:'空间',
                        desc:'后排空间偏小，车内空间小，后备箱空间不错'
                    },{
                        title:'外观',
                        desc:'前脸霸气，车尾造型不错，钣金厚实'
                    },{
                        title:'操控',
                        desc:'操控很灵活，底盘好，指向精准，轮胎抓地力强'
                    },{
                        title:'内饰',
                        desc:'内饰做工不错，硬塑料不喜欢，内饰风格特不错'
                    },{
                        title:'油耗',
                        desc:'瞬时油耗高，市区油耗特高'
                    },{
                        title:'配置',
                        desc:'配置最满意，倒车影像好用，车载导航不好用'
                    }
                ]
        }

    },
    {
        id:9,
        brandname:'日产', //品牌名称
        carname:'楼兰', //车型名称
        modelname:'', //车款名称
        imgurl:"http://47.105.100.82/0605/image600/Car_image_010.png",
        video:{
            url:"http://47.105.100.82/0605/Carvideo2400/Car_solo_010.mp4",
            url2:"http://47.105.100.82/0605/Carvideo1200/Car_compare_010.mp4",
            urlRoot:'http://47.105.100.82/0605/Merge/Car_compare',
            videoNum:'010',
            duration:360,                 //秒,
            slot:[
                {                         //时间段
                    time:0,
                    title:'亮点'
                },
                {
                    time:130,
                    title:'外观'
                },
                {
                    time:203,
                    title:'空间'
                },
                {
                    time:221,
                    title:'内饰'
                }
            ],
            twoslot:[
                {                         //时间段
                    time:0,
                    title:'外观'
                },
                {
                    time:73,
                    title:'空间'
                },
                {
                    time:91,
                    title:'内饰'
                }
            ],
            coords:[
                    {
                        start:0,
                        url:'../img/1_car.jpg'
                    },{
                        start:10,
                        url:'../img/2_car.jpg'
                    },{
                        start:20,
                        url:'../img/3_car.jpg'
                    },{
                        start:30,
                        url:'../img/4_car.jpg'
                    },{
                        start:40,
                        url:'../img/5_car.jpg'
                    },{
                        start:50,
                        url:'../img/6_car.jpg'
                    },{
                        start:60,
                        url:'../img/7_car.jpg'
                    },{
                        start:70,
                        url:'../img/8_car.jpg'
                    },{
                        start:80,
                        url:'../img/9_car.jpg'
                    },{
                        start:90,
                        url:'../img/10_car.jpg'
                    }
            ]
        },
        koubei:{
                detail:[
                    {                   //配置
                        title:'动力',
                        desc:'动力表现挺好，超车动力够，动力平顺'
                    },{
                        title:'舒适性',
                        desc:'舒适性不错，悬挂舒适度好，风噪蛮大'
                    },{
                        title:'空间',
                        desc:'空间大，后备箱空间大，后排空间蛮拥挤'
                    },{
                        title:'外观',
                        desc:'车漆较薄，车头设计好看'
                    },{
                        title:'操控',
                        desc:'操控满意，底盘舒服，转向挺精准'
                    },{
                        title:'内饰',
                        desc:'内饰塑料感太强，内饰做工不错，中控塑料感太强'
                    },{
                        title:'油耗',
                        desc:'综合油耗不高，市区油耗也不是很高，油箱太小'
                    },{
                        title:'配置',
                        desc:'配置高大上，没有定速巡航，倒车影像不是很清晰'
                    }
                ]
        }

    },
    {
        id:10,
        brandname:'大众', //品牌名称
        carname:'途昂', //车型名称
        modelname:'', //车款名称
        imgurl:"http://47.105.100.82/0605/image600/Car_image_005.png",
        video:{
            url:"http://47.105.100.82/0605/Carvideo2400/Car_solo_005.mp4",
            url2:"http://47.105.100.82/0605/Carvideo1200/Car_compare_005.mp4",
            urlRoot:'http://47.105.100.82/0605/Merge/Car_compare',
            videoNum:'005',
            duration:360,                 //秒,
            slot:[
                 {                         //时间段
                  time:0,
                  title:'亮点'
              },
              {
                  time:60,
                  title:'外观'
              },
              {
                  time:80,
                  title:'空间'
              },
              {
                  time:120,
                  title:'内饰'
              },
              {
                  time:180,
                  title:'动力'
              }
            ],
            twoslot:[
                {                         //时间段
                    time:0,
                    title:'外观'
                },
                {
                    time:73,
                    title:'空间'
                },
                {
                    time:91,
                    title:'内饰'
                }
            ],
            coords:[
                    {
                        start:0,
                        url:'../img/1_car.jpg'
                    },{
                        start:10,
                        url:'../img/2_car.jpg'
                    },{
                        start:20,
                        url:'../img/3_car.jpg'
                    },{
                        start:30,
                        url:'../img/4_car.jpg'
                    },{
                        start:40,
                        url:'../img/5_car.jpg'
                    },{
                        start:50,
                        url:'../img/6_car.jpg'
                    },{
                        start:60,
                        url:'../img/7_car.jpg'
                    },{
                        start:70,
                        url:'../img/8_car.jpg'
                    },{
                        start:80,
                        url:'../img/9_car.jpg'
                    },{
                        start:90,
                        url:'../img/10_car.jpg'
                    }
            ]
        },
        koubei:{
                detail:[
                    {                   //配置
                        title:'动力',
                        desc:'动力特足，超车动力很充足，变速箱换档好'
                    },{
                        title:'舒适性',
                        desc:'舒适性不错，隔音效果好，底盘过滤好'
                    },{
                        title:'空间',
                        desc:'空间大，横向空间好，储物空间大'
                    },{
                        title:'外观',
                        desc:'前脸造型非常的时尚，大灯设计好看，板金厚实'
                    },{
                        title:'操控',
                        desc:'操控不错，悬挂系统棒，指向精准'
                    },{
                        title:'内饰',
                        desc:'小细节棒，内饰风格很强，中控台样式蛮新颖'
                    },{
                        title:'油耗',
                        desc:'油耗方面特别满意'
                    },{
                        title:'配置',
                        desc:'配置高，倒车影像较准，没有定速巡航'
                    }
                ]
        }

    },
    {
        id:11,
        brandname:'广汽传祺', //品牌名称
        carname:'GS8', //车型名称
        modelname:'', //车款名称
        imgurl:"http://47.105.100.82/0605/image600/Car_image_006.png",
        video:{
            url:"http://47.105.100.82/0605/Carvideo2400/Car_solo_006.mp4",
            url2:"http://47.105.100.82/0605/Carvideo1200/Car_compare_006.mp4",
            urlRoot:'http://47.105.100.82/0605/Merge/Car_compare',
            videoNum:'006',
            duration:360,                 //秒,
            slot:[
                 {                         //时间段
                  time:0,
                  title:'亮点'
              },
              {
                  time:60,
                  title:'外观'
              },
              {
                  time:80,
                  title:'空间'
              },
              {
                  time:120,
                  title:'内饰'
              },
              {
                  time:180,
                  title:'动力'
              }
            ],
            twoslot:[
                {                         //时间段
                    time:0,
                    title:'外观'
                },
                {
                    time:73,
                    title:'空间'
                },
                {
                    time:91,
                    title:'内饰'
                }
            ],
            coords:[
                    {
                        start:0,
                        url:'../img/1_car.jpg'
                    },{
                        start:10,
                        url:'../img/2_car.jpg'
                    },{
                        start:20,
                        url:'../img/3_car.jpg'
                    },{
                        start:30,
                        url:'../img/4_car.jpg'
                    },{
                        start:40,
                        url:'../img/5_car.jpg'
                    },{
                        start:50,
                        url:'../img/6_car.jpg'
                    },{
                        start:60,
                        url:'../img/7_car.jpg'
                    },{
                        start:70,
                        url:'../img/8_car.jpg'
                    },{
                        start:80,
                        url:'../img/9_car.jpg'
                    },{
                        start:90,
                        url:'../img/10_car.jpg'
                    }
            ]
        },
        koubei:{
                detail:[
                    {                   //配置
                        title:'动力',
                        desc:'加速动力十足，换挡平顺'
                    },{
                        title:'舒适性',
                        desc:'座椅材料舒适性较好，高速胎噪控制较差'
                    },{
                        title:'空间',
                        desc:'乘坐空间较大，腿部空间够用，储物空间有限'
                    },{
                        title:'外观',
                        desc:'尾灯帅，侧面腰线好看'
                    },{
                        title:'操控',
                        desc:'路感反馈清洗，转向精准，底盘悬挂扎实'
                    },{
                        title:'内饰',
                        desc:'内饰做工精准，气氛灯好看'
                    },{
                        title:'油耗',
                        desc:'高速油耗满意，室内可经济模式省油'
                    },{
                        title:'配置',
                        desc:'自动加速定速巡航好用，主动刹车时亮点'
                    }
                ]
        }

    }
]
